# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston
import warnings
warnings.filterwarnings('ignore')
data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [4]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [5]:
y.head()

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [6]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X, y, train_size=0.8, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [7]:
from sklearn.linear_model import LinearRegression


linreg=LinearRegression()

In [8]:
linreg.fit(X_train, y_train)


LinearRegression()

In [11]:
linreg.predict(X_train)[:5]

array([[10.96952405],
       [19.41196567],
       [23.06419602],
       [12.1470648 ],
       [18.3738116 ]])

In [17]:
y_pred = linreg.predict(X_test)
y_pred[:5]

array([[28.99672362],
       [36.02556534],
       [14.81694405],
       [25.03197915],
       [18.76987992]])

## 3. Calculate and print R-squared for both the training and the testing set.

In [13]:
linreg.score(X_train, y_train)


0.7508856358979673

## 4. Calculate and print mean squared error for both the training and the testing set.

In [20]:
from sklearn.metrics import mean_squared_error as mse  


mse(y_test, y_pred, squared = False)

4.92860218266536

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [22]:
from sklearn.metrics import mean_absolute_error as mae  

mae(y_test, y_pred)

3.1890919658878656

## Classification Model Evaluation

In [23]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [24]:
X_train, X_test, y_train, y_test = tts(X, y, train_size=0.8, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120, 1), (30, 1))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [29]:
from sklearn.linear_model import LogisticRegression as LogReg
logreg = LogReg()
logreg.fit(X_train, y_train)

LogisticRegression()

In [67]:
logreg.predict(X_train)

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [66]:
logreg.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [46]:
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print(train_accuracy)
print(test_accuracy)

0.975
1.0


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [56]:
from sklearn.metrics import balanced_accuracy_score as bas

In [65]:
bas(y_train, y_train_pred)

0.975609756097561

In [64]:
bas(y_test, y_test_pred)

1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [60]:
from sklearn.metrics import precision_score as ps

In [70]:
ps(y_train, y_train_pred, average= 'macro')

0.9761904761904763

In [71]:
ps(y_test, y_test_pred, average= 'macro')

1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [72]:
from sklearn.metrics import recall_score as rec

In [74]:
rec(y_train, y_train_pred, average= 'macro')

0.975609756097561

In [75]:
rec(y_test, y_test_pred, average= 'macro')

1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [78]:
from sklearn.metrics import f1_score as f1

In [81]:
f1(y_train, y_train_pred, average= 'macro')

0.9749960931395533

In [80]:
f1(y_test, y_test_pred, average= 'macro')

1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [83]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_train_pred)
print(cm)

[[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]


In [84]:
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.