# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

/Users/monicaclaroscadima/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Cal

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [4]:
from sklearn.model_selection import train_test_split

X = data.drop('MEDV', axis=1)
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size=0.2)

In [5]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404,), (102,))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [6]:
from sklearn.linear_model import LinearRegression
LinearRegression=LinearRegression()

In [7]:
LinearRegression.fit(X_train, y_train)

LinearRegression()

In [8]:
LinearRegression.predict(X_test)[:10]

array([26.01412768, 26.39261086, 14.49665464, 22.04007957, 19.3049305 ,
       27.8549541 , 21.8665419 , 17.21902069, 20.66552349, 21.40983115])

In [9]:
y_pred_test = LinearRegression.predict(X_test)

In [10]:
y_pred_test

array([26.01412768, 26.39261086, 14.49665464, 22.04007957, 19.3049305 ,
       27.8549541 , 21.8665419 , 17.21902069, 20.66552349, 21.40983115,
       21.08016383, 12.6703647 , 27.99209674, 19.05648701, 31.06018341,
       13.41832193, 16.73305087, 25.19978964, 31.36749446, 35.85587202,
       18.92630111, 27.79603816, 18.52108044, 32.75490902,  5.77908379,
       16.1081385 , 12.4621236 , 35.88164598, 27.65647951, 20.31910027,
       22.82454012, 29.70170617, 19.68302163, 35.60107409, 26.62018785,
       40.19452046, 21.63870799, 20.16088687, 18.00671541, 23.47216931,
       31.04975825, 35.84373282, 32.07668513, 44.09004288, 19.74255906,
       18.6832378 , 16.16104787, 10.02528449, 33.55035477, 15.28004964,
       23.91190441, 18.38998102, 23.22560834, 21.94735627, 10.24173607,
       23.62284294,  6.26609142, 14.2434001 , 24.22898868, 27.10720368,
       28.18869844, 17.62792691, 20.48697203, 17.09780237, 21.02239437,
       18.48764703, 15.60735927, 25.10481022, 21.51093333, 31.69

In [11]:
y_pred_train = LinearRegression.predict(X_train)
y_pred_train

array([ 1.62215141, 22.71641343, 27.44165935, 20.22554331, 15.69515421,
       16.87123167, 37.85246013, 20.32605294, 34.60495572, 33.45028271,
       25.15431806, 21.26949051, 28.72703086, 10.25844865, 24.48284972,
       25.15599357, 20.50357029, 23.4046786 , 23.7480525 , 22.67458236,
       13.78286875, 24.60403223, 21.48169343, 12.85466958, 18.42478112,
       16.81431226, 30.61806361, 28.77770824, 23.05947685, 34.89884068,
       17.84619766, 26.856914  , 24.95986462, 16.89479575, 18.06886219,
       19.55881738, 19.29894011, 38.43740143, 30.55215892, 13.80089061,
       21.85138578, 19.0852986 , 11.76280692, 13.43339588, 24.71004582,
       26.92901935, 20.9675478 , 21.93602471, 38.68462075, 14.95646524,
        9.41870422, 30.27184113, 23.23738552, 18.33891528, 25.04722578,
       24.81131657, 22.75609032, 13.92751101, 23.35965603, 21.6638455 ,
       13.25565603, 18.54405809, 38.86978074, 22.39992389, 22.1299385 ,
        8.77734389, 15.76600988, 31.76650765, 37.17377174, 40.26

## 3. Calculate and print R-squared for both the training and the testing set.

In [12]:
from sklearn.metrics import r2_score as r2

LinearRegression.score(X_test, y_test)

0.7580192831976063

In [13]:
LinearRegression.score(X_train, y_train)

0.7331584519433528

## 4. Calculate and print mean squared error for both the training and the testing set.

In [14]:
from sklearn.metrics import mean_squared_error


In [15]:
mean_squared_error(y_test, y_pred_test)

22.577739820525437

In [16]:
mean_squared_error(y_train, y_pred_train)

21.906711513483593

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [17]:
from sklearn.metrics import mean_absolute_error

In [18]:
mean_absolute_error(y_test, y_pred_test)

3.373427615738126

In [19]:
mean_absolute_error(y_train, y_pred_train)

3.26865359339775

## Classification Model Evaluation

In [20]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [21]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [22]:
X = data.drop('class', axis=1)
y = data['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size=0.2)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LogisticRegression as LogReg
logreg=LogReg()

In [27]:
logreg.fit(X_train, y_train)

y_pred_test=logreg.predict(X_test)

y_prob=logreg.predict_proba(X_test)

y_pred_test[:10]

array([0, 1, 0, 0, 1, 2, 1, 2, 0, 0])

In [28]:
y_prob[:2]

array([[9.84628806e-01, 1.53711849e-02, 8.78099500e-09],
       [2.69867485e-02, 9.53061276e-01, 1.99519753e-02]])

In [29]:
y_pred_train=logreg.predict(X_train)

y_prob_train=logreg.predict_proba(X_train)

y_pred_test[:10]

array([0, 1, 0, 0, 1, 2, 1, 2, 0, 0])

In [30]:
y_prob_train[:2]

array([[9.46925300e-01, 5.30743705e-02, 3.29515071e-07],
       [1.74828868e-02, 9.64066521e-01, 1.84505927e-02]])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [31]:
from sklearn.metrics import accuracy_score as acc

In [32]:
acc(y_train, y_pred_train)

0.975

In [33]:
acc(y_test, y_pred_test)

0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [34]:
from sklearn.metrics import balanced_accuracy_score

In [35]:
balanced_accuracy_score(y_train, y_pred_train)

0.9743589743589745

In [36]:
balanced_accuracy_score(y_test, y_pred_test)

0.9583333333333334

## 10. Calculate and print the precision score for both the training and the testing set.

In [37]:
from sklearn.metrics import precision_score as prec

prec(y_test, y_pred_test, average=None)

array([1.        , 0.91666667, 1.        ])

In [38]:
prec(y_train, y_pred_train, average=None)

array([1.        , 1.        , 0.93333333])

## 11. Calculate and print the recall score for both the training and the testing set.

In [39]:
from sklearn.metrics import recall_score as rec

rec(y_test, y_pred_test, average=None)

array([1.   , 1.   , 0.875])

In [40]:
rec(y_train, y_pred_train, average=None)

array([1.        , 0.92307692, 1.        ])

## 12. Calculate and print the F1 score for both the training and the testing set.

In [41]:
from sklearn.metrics import f1_score as f1

f1(y_test, y_pred_test, average = None)

array([1.        , 0.95652174, 0.93333333])

In [42]:
f1(y_train, y_pred_train, average=None)

array([1.        , 0.96      , 0.96551724])

## 13. Generate confusion matrices for both the training and the testing set.

In [43]:
from sklearn.metrics import confusion_matrix as cm

cm(y_test, y_pred_test)

array([[11,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  7]])

In [44]:
cm(y_train, y_pred_train)

array([[39,  0,  0],
       [ 0, 36,  3],
       [ 0,  0, 42]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.